# Generated by Django 6.0.6 on 2026-06-26 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Synopsis')),
                ('affiche', models.ImageField(upload_to='films/affiches/', verbose_name='Affiche')),
                ('bande_annonce_url', models.URLField(blank=True, verbose_name='Lien bande-annonce (YouTube)')),
                ('lien_video', models.URLField(blank=True, help_text="⚠️ Ne pas téléverser de gros fichiers vidéo ici sur Render gratuit (le disque est effacé à chaque redéploiement). Hébergez la vidéo sur YouTube en 'non listé', Cloudinary ou Bunny.net, puis collez le lien ici.", verbose_name='Lien vidéo complet (YouTube non listé / Cloudinary / Bunny.net)')),
                ('fichier_video', models.FileField(blank=True, help_text="À utiliser uniquement en développement local. Préférez 'lien_video' en production.", null=True, upload_to='films/videos/', verbose_name='Fichier vidéo (local — déconseillé sur Render gratuit)')),
                ('annee_sortie', models.PositiveIntegerField(verbose_name='Année de sortie')),
                ('duree_minutes', models.PositiveIntegerField(verbose_name='Durée (minutes)')),
                ('realisateur', models.CharField(blank=True, max_length=150, verbose_name='Réalisateur')),
                ('note', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Note /10')),
                ('a_la_une', models.BooleanField(default=False, verbose_name='Mettre à la une')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, to='films.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Synopsis')),
                ('affiche', models.ImageField(upload_to='series/affiches/', verbose_name='Affiche')),
                ('bande_annonce_url', models.URLField(blank=True, verbose_name='Lien bande-annonce (YouTube)')),
                ('annee_debut', models.PositiveIntegerField(verbose_name='Année de début')),
                ('nombre_saisons', models.PositiveIntegerField(default=1, verbose_name='Nombre de saisons')),
                ('note', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Note /10')),
                ('a_la_une', models.BooleanField(default=False, verbose_name='Mettre à la une')),
                ('publie', models.BooleanField(default=True, verbose_name='Publiée')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, to='films.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ListeAVoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_a_voir', to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.serie')),
            ],
            options={
                'verbose_name': 'Élément de la liste à voir',
                'verbose_name_plural': 'Liste à voir',
                'ordering': ['-ajoute_le'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.PositiveIntegerField(verbose_name='Saison')),
                ('numero', models.PositiveIntegerField(verbose_name="Numéro de l'épisode")),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'épisode")),
                ('lien_video', models.URLField(blank=True, help_text='Privilégiez ce champ plutôt que le fichier local sur Render gratuit.', verbose_name='Lien vidéo (YouTube non listé / Cloudinary / Bunny.net)')),
                ('fichier_video', models.FileField(blank=True, null=True, upload_to='series/episodes/', verbose_name='Fichier vidéo (local — déconseillé sur Render gratuit)')),
                ('duree_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='films.serie', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Épisode',
                'verbose_name_plural': 'Épisodes',
                'ordering': ['saison', 'numero'],
                'unique_together': {('serie', 'saison', 'numero')},
            },
        ),
    ]
